### PR TITLE
Add `Kakele Online` to the list of featured games.

### PR DESCRIPTION
**Pull request by lucas-kakele**
Hi folks.

I'm Lucas, one of the creators of Kakele Online ([kakele.io](http://kakele.io/)), a MMORPG we developed inspired by the games we played in our childhood.

We used libGDX for the game client, and it is a great lib. I'm creating this PR to list Kakele in libgGDX's showcase page ([libgdx.com/showcase](http://libgdx.com/showcase)).

Let me know if I should follow a different process.

Thanks!

### CODE REVIEW

**Comment by lucas-kakele** [comment]
Hi @crykn! Thanks for triaging this PR.

Is there any information you need on my end to review it?

Thanks!

**Comment by crykn** [comment]
Hey! 

> Is there any information you need on my end to review it?

No, I'd just like to give members of the team/the community some time to chime in on this. Amending the showcase list is always a bit of a tricky topic. Ideally, we'd like to provide a list of many distinctively different games, showing various features/styles/designs that are possible with libGDX. But deciding this is always subjective, so I'd rather not do it alone.

**Comment by Frosty-J** [comment]
It's obviously a serious project so seems like a good fit for the list to me.

**Comment by lucas-kakele** [comment]
Thank you folks!

**Pull request merged**
