### PR TITLE
Necessary documentation changes for libGDX 1.10.1

### PR DESCRIPTION
**Pull request by crykn**
Needs to be merged after the next libGDX release. Previously #28.

### CODE REVIEW

**Comment by Frosty-J** [comment]
Here's a crazy idea: How about merging this now? You might be thinking that libGDX 1.10.1 (more realistically 1.11.0 at this rate) isn't here yet, and you'd be absolutely right. Doesn't look like this PR/branch contains any major changes beyond the setup tool.

The rate at which Java 16/17 users have issues with gdx-setup is a nuisance and doesn't leave a good first impression of libGDX. I'm not sure if they have a misconfigured `JAVA_HOME` or what, as they're often adamant that it's being launched with Java 8 (or some other compatible version). And we have Java 18 on the horizon, though I'm not personally expecting Gradle or us to support it until April.

https://github.com/libgdx/libgdx.github.io/blob/3cfbad8c2e6c576c5438f343008f35e0a3203af1/wiki/start/project-generation.md?plain=1#L14-L15

My/our proposal is to remove the stable download link, making the nightly one the only download. This can be a temporary measure until the release cycle gets back on track.

```html
<a href="https://libgdx-nightlies.s3.eu-central-1.amazonaws.com/libgdx-runnables/gdx-setup.jar" class="btn btn--success">Download</a>
```

**Comment by tommyettinger** [comment]
Maybe leave a link to the stable one somewhere (wiki, maybe?) but make sure the nightly is in plain sight and will be the first link people click. The Discord has been stuffed to the gills with problems relating to the stable gdx-setup lately, and I think it would really help if the stable version was hidden or removed.

**Comment by Tom-Ski** [comment]
the setup tool should not be part of libgdx tbh. The release cycle is not the same, and for that reason, gdx-setup was only ever downlable from the snapshot, not some old archived version of the release build as all the dependencies and toolchains update far faster than libgdx

**Comment by crykn** [comment]
The main concern with just providing the snapshots of gdx-setup was that whenever the build templates change and use "new" stuff (only available in the libGDX _snapshot_), the nightly setup tool will break, as it still depends on the last _stable_ release of libGDX.    But I guess for the time being, the rewards outweigh the risks. See 307791b9e2af9a55ee91175e49c64426d71b4009.

Consequently, I'll also merge this PR, so the documentation is adapted to the LWJGL 3 changes.

**Comment by obigu** [comment]
It may be ok as a temporary solution until we make a new release of libGDX because there's so many people running into this Java version specific problem but the only thingh that fixes both scenarios (toolchain and libGDX pushed changes that break Gdx Setup compatibility with latest stable) is to split Gdx Setup as an independent project with it's own release cycle. 

I'm not sure toolchain changes break stuff more often than libGDX does, at least it wasn't the case some time ago where the Gdx Setup snapshot (the only one that was available to download) kept being broken when using latest stable libGDX version. 

Unfortunately, the current frequency of libGDX releases makes these issues more visible.

**Comment by obigu** [comment]
I forgot to mention the other problem we had by only providing the Gdx Setup SNAPSHOT is that it depends on libGDX SNAPSHOT and, as expected, it's not as stable as the latest libGDX stable version and from time to time, users who downloaded the Gdx Setup to create their first projects where running into random issues not understanding what was going on. Default Gdx Setup should always depend on the latest stable version.

IMO manually deploying a new Stable binary with a hot fix for latest Java support (and keeping available both Stable and SNAPSHOT) is, for the moment, the best approach to this.

**Comment by Frosty-J** [comment]
> the other problem we had by only providing the Gdx Setup SNAPSHOT is that it depends on libGDX SNAPSHOT and, as expected, it's not as stable as the latest libGDX stable version

What do you mean? The nightly builds of gdx-setup use libGDX 1.10.0 in the project dependencies. Or do you just mean a problematic gdx-setup change might get merged? Because, yeah, that's possible as we've occasionally seen with libGDX itself.

**Comment by obigu** [comment]
> > the other problem we had by only providing the Gdx Setup SNAPSHOT is that it depends on libGDX SNAPSHOT and, as expected, it's not as stable as the latest libGDX stable version
> 
> What do you mean? The nightly builds of gdx-setup use libGDX 1.10.0 in the project dependencies. Or do you just mean a problematic gdx-setup change might get merged? Because, yeah, that's possible as we've occasionally seen with libGDX itself.

Oh, true, we have the opposite problem then, if SNAPSHOT Gdx Setup depends on stable libGDX we can't push Gdx Setup changes at the same time (in the same PR) we push the libGDX breaking change, being only able to push those "pending changes" after the libGDX release has been made. Gdx Setup SNAPSHOT should depend on libGDX latest SNAPSHOT to be able to build and test a project with the latest SNAPSHOT, otherwise, what's the point?

**Comment by tommyettinger** [comment]
And of course there's always Liftoff as the existing not-part-of-libGDX project with actual release structure, that could be linked to anywhere in the page.

**Pull request merged**
